# Codecov configuration for Swift Package
coverage:
  status:
    project:
      default:
        target: 80  # Coverage threshold target for entire project
        threshold: 1%  # Allowable variance for target
    patch:
      default:
        target: 80  # Coverage threshold for pull requests
        threshold: 1%
        
comment:
  layout: "reach, diff, flags, files"
  behavior: default  # Post a comment for coverage
  require_changes: false  # Don't require changes for coverage comments

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

swift:
  package_manager: spm
  report_file: ".build/arm64-apple-macosx/debug/codecov/RouterKit.json"

flags:
  - swift

exclude:
  - Tests/*  # Exclude test files from coverage
  - Example/*  # Example folder if exists

fixes:
  - "::Sources/"  # Fix file paths in reports, adjust as necessary
