# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0.0"

    - name: Get swift version
      run: swift --version
        
    - uses: actions/checkout@v4

    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Get code coverage path
      run: echo "path=$(swift test --show-codecov-path)" >> $GITHUB_OUTPUT
      
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -f ${{ steps.get-path.outputs.path }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
