# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Swift 6.0.0
      run: |
        brew install swift
        brew link swift --overwrite

    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
